name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy Files to EC2
      run: |
        scp -i ~/.ssh/ec2.pem -r * \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

    - name: Deploy Website
      run: |
        ssh -i ~/.ssh/ec2.pem \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          sudo cp -r /tmp/* /var/www/html/
          sudo systemctl restart nginx
        EOF
